### PR TITLE
 OWL/XML MimeType

### PR DESCRIPTION
**Pull request by fahadsiddiqui**

### CODE REVIEW

**Review by gabriel-vasile — COMMENTED** [review]
Hi,
`mimetype` already detects some XML subtypes. Is there a problem if `OwlXml` function would use the `xmlSig` just like atom, kml, and others do here https://github.com/gabriel-vasile/mimetype/blob/master/internal/matchers/text.go#L35 ?

**Comment by fahadsiddiqui** [comment]
That would be more convenient. Let me make the change.

**Comment by fahadsiddiqui** [comment]
@gabriel-vasile I have implemented it the way you described. Added test cases too. Can you please merge?

**Comment by fahadsiddiqui** [comment]
@gabriel-vasile I have resolved the conflicts, can you please merge this?

**Review by gabriel-vasile — APPROVED** [review]
Looks good!

**Pull request merged**
