### PR TITLE
Add RPM mime type

### LINKED ISSUE #84: Add support for RPM file format
1) Specify the MIME type and extension for which to add support
application/x-rpm
2) Share an example file
convert existing test deb file into RPM:
$ cd mimetype/testdata && sudo alien -r deb.deb
3) Optionally, add a reference to the specification of the file format.
[https://github.com/file/file/blob/fd04f3df822e3934c557cf282615a61c04ca2324/magic/Magdir/rpm](https://github.com/file/file/blob/fd04f3df822e3934c557cf282615a61c04ca2324/magic/Magdir/rpm)

### PR DESCRIPTION
**Pull request by pippo**
Resolves #84

Reference:
https://github.com/file/file/blob/fd04f3df822e3934c557cf282615a61c04ca2324/magic/Magdir/rpm

### CODE REVIEW

**Comment by gabriel-vasile** [comment]
Hi @pippo, as far as I can see, there is also [delta RPM](https://www.pks.mpg.de/~mueller/docs/suse10.2/html/opensuse-manual_en/manual/sec.rpm.delta.html) files which have the same MIME type, but different signature. Can you please change the code to detect these too?

**Comment by pippo** [comment]
Sure. I can give it a try. However, I couldn't find a test file for those.
I tried generating one myself on CentOS, but it did't match the [spec](https://github.com/file/file/blob/fd04f3df822e3934c557cf282615a61c04ca2324/magic/Magdir/rpm). Will try again later.

**Comment by pippo** [comment]
Gave it another try on OpenSUSE.

It appears to me that the referenced doc for [delta RPM](https://www.pks.mpg.de/~mueller/docs/suse10.2/html/opensuse-manual_en/manual/sec.rpm.delta.html) is a bit outdated. There seems to be no way to run `prepdeltarpm` and/or `writedeltarpm` on a recent OpenSUSE (15.1).

Although there's an alternative way to generate delta rpms using [deltarpm](https://software.opensuse.org/package/deltarpm) package, the result's signature is different from what's described [here](https://github.com/file/file/blob/fd04f3df822e3934c557cf282615a61c04ca2324/magic/Magdir/rpm) and matches the signature of a regular RPM.

```
# makedeltarpm hello-1-1.x86_64.rpm hello-1-2.x86_64.rpm hello-delta.x86_64.rpm
# xxd hello-delta.x86_64.rpm | head -1
00000000: edab eedb 0300 0000 0001 6865 6c6c 6f2d  ..........hello-
# xxd hello-1-2.x86_64.rpm | head -1
00000000: edab eedb 0300 0000 0001 6865 6c6c 6f2d  ..........hello-
```

All that said, I'd rather merge this PR as-is and add alternative(/legacy) signature for delta RPMs later on, once (and if) such a use case arises.

What are your thoughts, @gabriel-vasile?

**Comment by gabriel-vasile** [comment]
Hi, I had a look at the source of [delarpm](https://github.com/rpm-software-management/deltarpm) and it has the `-r` option for "old rpm" format.
Can you please try with
`makedeltarpm -r hello-1-1.x86_64.rpm hello-1-2.x86_64.rpm hello-delta.x86_64.rpm`?
If it works, great, if it doesn't I will just merge this.

**Comment by pippo** [comment]
Yes, it worked alright with`-r`. I missed that. Thank you.
I pushed a change for delta rpms. Please, take a look.

**Pull request merged**
