### PR TITLE
Add support for detecting avif files

### PR DESCRIPTION
**Pull request by vansante**
I took a stab at implementing this. Let me know if it needs more work :smiley:

### CODE REVIEW

**Review by gabriel-vasile — COMMENTED** [review]
Hi, sorry for the late response.
It seems like the sample image in this PR is a HEIF and not AVIF:
```bash
bash> file --mime avif.avif
image/heif; charset=binary
```
I was able to convert it to AVIF with:
```bash
mv avif.avif heif.heif # move to .heif because convert uses extension to detect source file format.
convert heif.heif avif.avif
```

**Comment by vansante** [comment]
Hey @gabriel-vasile,

I pulled the sample image from this [page](http://download.opencontent.netflix.com/?prefix=AV1/Chimera/AVIF/), which is supposed to be a list of sample AVIF images used by netflix. (I used [this](http://download.opencontent.netflix.com.s3.amazonaws.com/AV1/Chimera/AVIF/Chimera-AV1-10bit-1920x1080-6191kbps-162.avif) one I believe).

**Comment by gabriel-vasile** [comment]
This is tricky. 
It seems like those images are created by a new encoder Netflix is working on. It's weird they use the .avif extension but the file has the HEIF signature.
This needs more investigation to see if the Netflix images are HEIF or AVIF.

some references:
https://netflixtechblog.com/introducing-svt-av1-a-scalable-open-source-av1-framework-c726cce3103a
https://netflixtechblog.com/svt-av1-an-open-source-av1-encoder-and-decoder-ad295d9b5ca2

**Comment by gabriel-vasile** [comment]
*According to https://github.com/libvips/libvips/pull/1657
      older avif used to use the the heif 'ftypmif1' as well*


https://github.com/apache/tika/blob/9672e765887188021d446a98f1a6635a21d4ae8a/tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml#L5574-L5584

**Comment by gabriel-vasile** [comment]
Considering `ftypmif1` is not recommended for avif and both [github.com/file/file](https://github.com/file/file/blob/b56b58d499dbe58f2bed28e6b3c297fe7add992e/magic/Magdir/animation#L294-L299) and [github.com/apache/tika](https://github.com/apache/tika/blob/9672e765887188021d446a98f1a6635a21d4ae8a/tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml#L5574-L5584) consider `ftypmif1` as heif, I think we should do the same.
Also, the license [here](http://download.opencontent.netflix.com/?prefix=AV1/Chimera/AVIF/) claims the images belong to Netflix so we must follow [some rules](https://creativecommons.org/licenses/by-nc-nd/4.0/) (give credit, include original license) in order to use them. I think it's easier to swap the test image with another one. I found [this image](https://demo1.piwigo.com/picture?/2429) as a [heif here](https://github.com/asvinours/jpeg-to-heif/blob/master/images/kitty-551554_1920.jpg.heic) and it can be used with no restrictions.
Let me know if I can help you or if anything is unclear.

**Comment by gabriel-vasile** [comment]
Closing this in favor of #210.

**Pull request closed without merging**
