### PR TITLE
fix: 🔒 replace exe.exe to avoid security scan findings

### LINKED ISSUE #550: File `exe.exe` compiled with Go 1.12 contains inherent security vulnerabilities
Jfrog Xray finds inherent vulnerabilities in Go binaries compiled with Go 1.12, such as `testdata/exe.exe` in this repo. ([full report](https://gist.github.com/erikpaasonen/7bf7c24b4ad361eeef872eaea017d91e).) I found that replacing the executable with a binary compiled with Go 1.21 or above causes Xray to find zero of these vulnerabilities. (There is one medium finding when compiled on 1.20.14.) I'd like to suggest to go ahead and replace the `exe.exe` file, so that there are as few barriers as possible to consuming this very useful Go package.

This issue [has been alluded to in the past](https://github.com/gabriel-vasile/mimetype/issues/528), but no action was taken because security tooling in general ought to ignore test data. While I agree, I can also see how managing per-repo test data conventions and exceptions becomes exponentially compounded when inspecting Go package dependencies. So where possible, it would be more convenient overall if the vulnerabilities simply didn't exist in the first place.

From what I can tell, the `exe.exe` file is only used to check whether a file is a legit binary executable. (It may not even ever be executed directly?) It seems that an arbitrary binary would work here. I compiled a Hello World app in Go 1.22 with the following source code:
```go
package main

func main() {
	println("Hello World!")
	return
}
```
And I tested this replacement `exe.exe` file in my fork with success -- both with Jfrog Xray scan of my fork (before and after proving that the vulns go away) as well as validating that all the unit tests in `go.yml` GitHub Action workflow still pass (as long as the binary was compiled for the Windows platform, interestingly enough).

I do plan to submit a PR here with the binary that I tested once I obtain organizational permission for this OSS contribution.

### PR DESCRIPTION
**Pull request by erikpaasonen**
fixes #550 

I was unsure what the source code for the existing binary was, so I blindly tried with a simple Go package with this as `main.go`:
```go
package main

func main() {
	println("Hello World!")
	return
}
```
Happy to recompile on Go 1.22 if specific source code is needed for this binary.

### CODE REVIEW

**Comment by erikpaasonen** [comment]
For what it may be worth, here is the GH Actions run link where this binary file passed your unit tests in my fork: https://github.com/erikpaasonen/mimetype/actions/runs/9781337916

**Comment by erikpaasonen** [comment]
Apologies for the force push on this branch. I screwed up merge from my fork's `master` branch containing changes I had to put in to get my fork to run independently of this repo (which I do not intend to include in this PR to upstream).

**Comment by gabriel-vasile** [comment]
Thank you!


The updated exe file is smaller, but it's still 1.34MB. 
When cloning the repo, both old and updated exe will be downloaded. So this change will increase git history by 1.34MB, albeit compressed.

To avoid this increase in repo size, we can use a C Hello world program, which is only a few KB instead of 1MB. C uses dynamic linking, go uses static, that's where the difference comes from.
So, the 2 things I'll ask for:
1. compile a C hello world with something like `gcc -O3 -o exe.exe main.c` or use this 
[helloworld.zip](https://github.com/user-attachments/files/16131377/helloworld.zip)
2. confirm that the exe file does not trigger JFrog Xray

**Comment by erikpaasonen** [comment]
Great catch! I recompiled, however now the unit tests fail [in my fork's branch](https://github.com/erikpaasonen/mimetype/actions/runs/9843487514/job/27174787912):
> --- FAIL: TestDetect (1.01s)
    mimetype_test.go:251: File: exe.exe; Expected: application/vnd.microsoft.portable-executable != Detected: application/x-mach-binary; err: <nil>
    mimetype_test.go:259: File: exe.exe; Expected: application/vnd.microsoft.portable-executable != Detected: application/x-mach-binary; err: <nil>
    mimetype_test.go:264: File: exe.exe; Expected: application/vnd.microsoft.portable-executable != Detected: application/x-mach-binary; err: <nil>
--- FAIL: TestDetectReader (0.63s)
    mimetype_test.go:343: File: exe.exe; Mime: application/vnd.microsoft.portable-executable != DetectedMime: application/x-mach-binary; err: <nil>

I figure this is your area of expertise so I pushed the commit anyway to get feedback. Unsure whether the unit tests can be adjusted to allow for detecting this type or whether I really do need to wrestle the binary into `application/vnd.microsoft.portable-executable` (since that's what is [actually registered with IANA](https://www.iana.org/assignments/media-types/application/vnd.microsoft.portable-executable)).

Good news though: [the VirusTotal scan](https://www.virustotal.com/gui/file/8925cb5ca6498f0dc6835aaf81f00407fee7b0c1aaad81dbe9d110492b7b44e5?nocache=1) comes back clean, and can confirm that this file passes the Xray scan as well.

**Comment by gabriel-vasile** [comment]
For executable files Windows uses `portable executable` (PE).
MacOS, however, uses `mach`.

When compiling a program, by default, the compiler will generate the executable for current OS.
Because you are using MacOS, it generates `mach`.
But this PR needs an `exe` PE file, for Windows.

So the options to get a PE executable for Windows are:
1. from your MacOS machine do cross-compilation (cross-compilation means compiling for a different OS).
This option requires more effort. Cross-compiling is not easy. It's probably easier to start a Windows virtual machine on compile there.
3. use the `helloworld.zip` that I provided (only if Xray says it is clean)
4. use some exe file from https://github.com/pts/pts-tinype (if Xray says they are clean)

**Comment by erikpaasonen** [comment]
Yes, I wasn't sure whether this was a hard-and-fast requirement for this project:
> But this PR needs an exe PE file, for Windows.

Perhaps I should have directly said cross-compiling rather than abstract it by the phrase "wrestling the binary into [format]". 👍 

I'm uncomfortable proposing an executable which is being flagged as malicious (even if without merit) since the nature of this PR is to placate non-nuanced security tooling in the first place. If we trade one legit exception for another we've just shuffled the problem I'm trying to solve sideways. The file you provided has more VirusTotal detections than I'd like in my git commit history, so I'd prefer to cross-compile rather than use that one. Unfortunately every single executable in `pts-tinype` has at least one detection.

That said, [one of them](https://github.com/pts/pts-tinype/blob/master/hh3wa.exe) had only [a single detection](https://www.virustotal.com/gui/file/954721e77dc4c4f26d10346c55a40506fb76e4413ee2d3a7b00aca33a5a6c8a3), and that one is merely an "unsafe" AI score marking. Can't eliminate all outliers, but any reasonable/real-world security tooling would agree the prepondernace of evidence is that this file is safe enough.

So I'm least-uncomfortable with [consuming `hh3wa.exe` as `exe.exe` here](https://github.com/gabriel-vasile/mimetype/pull/551/commits/34734cb29bd16ef00693f1d3e4f627863b47d802) to save the hassle of cross compiling for Windows. (I don't personally have ready access to a Windows machine... would have to spin up a VM in a cloud provider or something.)

Jfrog Xray scan is also clean on this file. 👍

**Comment by chkp-erezca** [comment]
Hi,
I'm having the same issue with JFrog Xray. I'm using Go in Alpine Linux. Is there a new version with this fix? Currently the latest version I have is 1.4.4 and I get this error about Go 1.12.

**Comment by gabriel-vasile** [comment]
@chkp-erezca, please update to https://github.com/gabriel-vasile/mimetype/releases/tag/v1.4.5
@erikpaasonen, I will close this PR in favour of #561. Changing the file is a temporary fix (sooner or later, some AV will report again). Thank you for raising the issue.

**Pull request closed without merging**
